name: televerse
description: Televerse lets you create your own efficient Telegram bots with ease in Dart. Supports latest Telegram Bot API - 9.3!
version: 3.1.4
homepage: https://televerse.weaverlabs.ca
repository: https://github.com/theweaverlabs/televerse
topics:
  - telegram
  - bot
  - chat
  - telegram-bot-api
  - bot-framework

funding:
  - https://buymeacoffee.com/heysreelal

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dio: ^5.9.1
  freezed: ^3.2.5
  freezed_annotation: ^3.1.0
  http_parser: ^4.1.2
  json_annotation: ^4.10.0

dev_dependencies:
  build_runner: ^2.11.0
  json_serializable: ^6.12.0
  lints: ^6.1.0
  test: ^1.29.0
