name: televerse
description: Televerse lets you create your own efficient Telegram bots with ease in Dart. Supports latest Telegram Bot API - 6.7!
version: 1.10.11
homepage: https://github.com/HeySreelal/televerse

environment:
  sdk: ">=2.17.7 <4.0.0"

dependencies:
  dio: ^5.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
