name: televerse
description: Televerse lets you create your own efficient Telegram bots with ease in Dart. Supports latest Telegram Bot API - 7.1!
version: 1.15.0
homepage: https://github.com/HeySreelal/televerse
topics:
  - telegram
  - bot
  - chat
  - telegram-bot-api
  - bot-framework

environment:
  sdk: ">=2.17.7 <4.0.0"

dependencies:
  dio: ^5.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
